package com.hora.jnana.ui.screens

data class LimbSubItem(
    val name: String = "",
    val endsAt: String = ""
)

data class PanchangaState(
    val hora: String = "--",
    val horaSymbol: String = "",
    val horaNext: String = "--",
    val horaEnds: String = "--",
    val horaEndsAt: String? = null,
    val remaining: String = "--",
    val tithi: String = "--",
    val tithiEnds: String = "",
    val nakshatra: String = "--",
    val nakshatraEnds: String = "",
    val yoga: String = "--",
    val yogaEnds: String = "",
    val yogaList: List<LimbSubItem> = emptyList(),
    val karana: String = "--",
    val karanaEnds: String = "",
    val karanaList: List<LimbSubItem> = emptyList(),
    val vara: String = "--",
    val varaEnds: String = "",
    val samvatsara: String = "--",
    val samvatsaraEnds: String = "",
    val ayana: String = "--",
    val ayanaEnds: String = "",
    val rutu: String = "--",
    val rutuEnds: String = "",
    val masa: String = "--",
    val masaEnds: String = "",
    val paksha: String = "--",
    val pakshaEnds: String = "",
    val rahuKalam: String = "--",
    val gulika: String = "--",
    val yamaganda: String = "--",
    val abhijit: String = "--",
    val sunrise: String = "--",
    val sunset: String = "--",
    val sunriseAt: String = "--",
    val sunsetAt: String = "--",
    val nextSunriseAt: String = "--",
    val solarNoonAt: String = "--",
    val daylightMidpointAt: String = "--",
    val dayDuration: String = "--",
    val nightDuration: String = "--",
    val dayHoraList: List<com.hora.jnana.models.HoraListItem> = emptyList(),
    val nightHoraList: List<com.hora.jnana.models.HoraListItem> = emptyList(),
    val moonRasi: String = "--",
    val sunRasi: String = "--",
    val lastUpdated: String = "--",
    val lastUpdatedMillis: Long = 0,
    val isLoading: Boolean = false,
    val error: String? = null
)
